#!/bin/sh

export PATH=/out:/bin:/sbin:/usr/bin:/usr/sbin
chmod +x /out/*

# Mount virtual filesystems
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts
mount -t tmpfs tmpfs /out


# Spawn getty on tty1–tty6
for tty in 1 2 3 4 5 6; do
    /bin/login
done



while true; do
    wait
done
